---

name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Test OSX Setup Script.
        run: |
          defaults read > defaults.before
          set -eux
          sudo bash .osx --no-restart
          defaults read > defaults.after
          diff defaults.before defaults.after
